name: Docker Image CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci-build.yml'
      - 'rstudio-savoirfR.containerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r_version: [ 4.0.4]
    steps:
    - uses: actions/checkout@v2
  
    - name: Branch name
      run: echo running on branch ${{github.ref_name}} for ${{matrix.r_version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./rstudio-savoirfR.containerfile
        push: true
        pull: true
        build-args: |
            R_VERSION=${{matrix.r_version}}
        tags: |
          ghcr.io/${{github.repository}}:${{matrix.r_version}} 
